const CATALOG = [
  {
    id: 't0',
    name: 'BC Flat Black Standard',
    img1: '/images/catalog/track_00_1.jpeg',
    img2: '/images/catalog/track_00_2.jpeg',
    price: '3300',
    info: 'Классика от Independent! Прочные и надёжные подвески Independent Stage 11 подойдут для любого стиля и уровня катания!<br><br>Вес: 139 - 376 гр/шт,<br>144 - 387 гр/шт,<br>149 - 394 гр/шт.<br><br>Высота: 55 мм<br>Алюминиевый А356 Т6 Хэнгер и База<br>Ось из хромомолибденовой стали SCM435<br>Стальной кингпин 8 стандарта<br><br>Цена указана за 1 подвеску<br>Все подвески продаются только парами.',
    sale: '',
  },
  {
    id: 't1',
    name: 'INDEPENDENT Stage 11 BTG Speed Burgundy Silver Standard',
    img1: '/images/catalog/track_01_1.jpeg',
    img2: '/images/catalog/track_01_2.jpeg',
    price: '3400',
    info: 'Классика от Independent! Прочные и надёжные подвески Independent Stage 11 подойдут для любого стиля и уровня катания!<br><br>Вес: 139 - 376 гр/шт,<br>144 - 387 гр/шт,<br>149 - 394 гр/шт.<br><br>Высота: 55 мм<br>Алюминиевый А356 Т6 Хэнгер и База<br>Ось из хромомолибденовой стали SCM435<br>Стальной кингпин 8 стандарта<br><br>Цена указана за 1 подвеску<br>Все подвески продаются только парами.',
    sale: '',
  },
  {
    id: 't2',
    name: 'THUNDER TRUCKS TRK LT DISORDER',
    img1: '/images/catalog/track_02_1.jpeg',
    img2: '/images/catalog/track_02_2.jpeg',
    price: '3360',
    info: 'Thunder предлагают лёгкие, прочные и манёвренные подвески для скейта, которыми славится данный бренд. База, вешалка и кингпин сделаны из лёгкого и прочного алюминия.<br><br>Цена указана за 1 подвеску.<br>Продаются парами.',
    sale: '',
  },
  {
    id: 't3',
    name: 'ACE AF1 Purple Satin',
    img1: '/images/catalog/track_03_2.jpeg',
    img2: '/images/catalog/track_03_3.jpeg',
    price: '3510',
    info: 'Новая модель подвесок для скейтборда ACE AF1<br>Это те самые подвески, благодаря геометрии которых, Вы сможете закладывать самые лютые углы в радиусах и быть на полных лузах в стрите. Если еще не катались на Ace - самое время попробовать!<br><br>Цена указана за 1 подвеску,<br>Все подвески продаются только парами.',
    sale: '',
  },
]