const CATALOG = [
  {
    id: 's0',
    name: 'Дека Toy Machine 2022',
    img1: '/images/catalog/skate_00_1.jpeg',
    img2: '/images/catalog/skate_00_2.jpeg',
    price: '6320',
    info: 'Коллекция 2023<br>Классическая дека из 7-слойного канадского клёна подойдет для любого уровня катания и места, будь то улица или скейт-парк.<br>Размер: 8.38 x 32<br>Конкейв: Medium',
    sale: '',
  },
  {
    id: 's1',
    name: 'Дека Fucking Awesome 2023',
    img1: '/images/catalog/skate_01_1.jpeg',
    img2: '/images/catalog/skate_01_2.jpeg',
    price: '6000',
    info: 'Чертовски крутая коллекция Printemps 2023.<br>Джино Яннуччи Pro Modele.<br>Размер: 8.25 x 31.9<br>Налет на рукоятке Джессупа Офферте',
    sale: '',
  },
  {
    id: 's2',
    name: 'Дека Foundation 2022',
    img1: '/images/catalog/skate_02_1.jpeg',
    img2: '/images/catalog/skate_02_2.jpeg',
    price: '5700',
    info: 'Классика от Foundation Skateboards не стареет. Бренд был основан в 1989 году и до сих пор остаётся в топе! Классическая дека из 7-слойного канадского клёна подойдет для любого уровня катания и места, будь то улица или скейт-парк.<br><br><br>Коллекция 2022<br>Размер: 8.75 x 32.61<br>Колесная база: 14.5<br>Ноуз: 7.25<br>Тэйл: 6.75<br>Конкейв: Medium',
    sale: '',
  },
  {
    id: 's3',
    name: 'ENJOI KITTEN RIPPER HYB PINK',
    img1: '/images/catalog/skate_03_1.jpeg',
    img2: '',
    price: '5820',
    info: 'Коллекция 2023<br><br>Resin Hybrid Construction - новые 7-слойные гибридные деки с двумя видами дерева. Слои склеиваются между собой эпоксидным клеем и часть слоёв шпона с помощью эпоксидной смолы Epoxy Resin, что обеспечивает минимальный вес скейтборда. Ключевое преимущество данной технологии - индивидуально прессованные деки, отличаются своей долговечностью!<br><br>Размер: 7.75" x 31.18"<br>Колёсная база: 13.87"<br>Full Concave / Steep Kick',
    sale: '',
  },
  {
    id: 's4',
    name: 'ZERO THOMAS - SAVE MY SOUL',
    img1: '/images/catalog/skate_04_1.jpeg',
    img2: '',
    price: '7990',
    info: 'Поставка: Февраль 2022<br>Размер: 8.25" x 31.9"<br>Колёсная база: 14.25"Про-модель: Jamie Thomas<br>100% Канадский клён',
    sale: '25',
  },
  {
    id: 's5',
    name: 'FLIP TEAM HKD RED DECK',
    img1: '/images/catalog/skate_05_1.jpeg',
    img2: '/images/catalog/skate_05_2.jpeg',
    price: '6250',
    info: 'Компанию Flip Skateboards хорошо знают в мире скейтбординга. Начиная с 1991 года бренд производит высококачественные скейтборды, деки, колёса, одежду и различные аксессуары для скейтбординга.<br><br>Коллекция 2022<br>Размер: 8,13" x 32"<br>Колёсная база: 14.2"<br>Ноуз: 6.9"<br>Тэйл: 6.7"<br>100% канадский клён<br>Производство: Испания, завод «HLC»',
    sale: '10',
  },
]